### ISSUE TITLE
" converted to ' in node.js examples

### ISSUE THREAD

**Issue by arve0** [ODataOrg/home-samples#6]
Which yields invalid code in Step 2 line 3:
![image](https://cloud.githubusercontent.com/assets/4810521/8511948/5197814a-232d-11e5-92c4-8bdf9ffd4b6b.jpg)

**Comment by arve0** [comment]
I see that it's already reported in #5.

**Comment by dingeins** [comment]
Yes, it is. Thank you for reporting. We'll fix it soon.

**Comment by dingeins** [comment]
Close this one.

**Comment by arve0** [comment]
https://github.com/ODataOrg/odataorg.github.io/issues/61
